"""Compute Pi0 in Python, keeping MEEP's C++ stepper for the operator S.

Pi0 is the affine constant of the EM-WaveHoltz iteration -- the filtered
response to the source over one window started from rest.  The rest of the
machinery (S, the filter, the injector, the timestep) is verified correct, so
this module removes MEEP's ``Source`` machinery from the Pi0 path and drives
the forcing from Python instead.

Why it is exact
---------------
The Yee E-update is

    E^{n+1} = E^n + (dt/eps) (curl H^{n+1/2} - J^{n+1/2}),

and a source-free ``sim.fields.step()`` performs exactly the first two terms.
Adding ``-(dt/eps) J^{n+1/2}`` to Ez immediately afterwards therefore
reproduces the forced update exactly.  With eps = 1 it is a plain array
addition, and ``initialize_field`` accumulates (``f += val``) at exactly the
Yee points.

The property that matters: Pi0 and S are then generated by the *same* discrete
operator, because both are driven by ``fields.step()`` on the same source-free
simulation.  Nothing about grid, boundaries or timestep can drift between them.

Injection happens **after** ``step()``, never before: MEEP updates B/H first
using the current E, so pre-injecting would corrupt the H update.

Scope: eps = mu = 1 and no PML.  With PML the current enters the D-update and E
is reconstructed through auxiliary variables, so post-hoc addition to E is no
longer equivalent to a current.
"""

import math

import meep as mp
import numpy as np

from .core import INJECT_AS
from .gridmap import make_injector


def forcing_amplitude(kind, omega, dt, n):
    """Time factor g multiplying J at step n (n = 1..M).

    ``"paper"``  sin(omega t^{n-1/2})           -- eq. (23a), the correct scheme
    ``"meep"``   sinc(w dt/2) sin(omega n dt)   -- what MEEP was measured to do
                 (scripts/probe_timing.py: amplitude sinc(w dt/2) exactly, but
                 sampled at t = dt rather than the half step dt/2)
    """
    if kind == "paper":
        return math.sin(omega * (n - 0.5) * dt)
    if kind == "meep":
        half = 0.5 * omega * dt
        return (math.sin(half) / half) * math.sin(omega * n * dt)
    raise ValueError(f"unknown forcing {kind!r}")


def compute_pi0_python(wh, J, forcing="paper", method="dft", component=mp.Ez,
                       eps=1.0, report=None):
    """Pi0 for a source-free EMWaveHoltz, with the forcing applied from Python.

    ``wh`` must wrap a simulation with **no MEEP sources** -- then ``apply_pi``
    is exactly S and this function supplies the forcing.  ``J`` is the spatial
    current profile on ``wh.grids[component]``.

    ``method="python"`` accumulates the filter by reading the whole Yee lattice
    every step (slow, obviously correct).  ``method="dft"`` reuses the native
    DFT accumulator and corrects it in closed form: the DFT samples inside
    ``step()``, i.e. *before* our injection, so it sees ``E^n - s_n`` with
    ``s_n = -(dt/eps) g(t_n) J``.  The deficit is a known scalar times a fixed
    spatial profile:

        Pi0 = Pi0_dft + C J,
        C = -(2 dt^2 / (T eps)) sum_n (cos(omega t_n) - 1/4) g(t_n)

    Returns a dict shaped like ``wh.zero()``.
    """
    if method not in ("python", "dft"):
        raise ValueError(f"unknown method {method!r}")

    sim = wh.sim
    grid = wh.grids[component]
    if J.shape != grid.shape:
        raise ValueError(f"J has shape {J.shape}, expected {grid.shape}")

    dt = sim.fields.dt
    omega, T, M = wh.omega, wh.T, wh.M
    misses = 0

    sim.restart_fields()
    acc = np.zeros(grid.shape) if method == "python" else None

    for n in range(1, M + 1):
        sim.fields.step()                     # free evolution; DFT samples here

        g = forcing_amplitude(forcing, omega, dt, n)
        # The source enters the D-update, and a write to E would be discarded
        # by update_eh on the next step, so the increment goes into D.
        increment = -dt * g * J
        if increment.any():
            cb, stats = make_injector(grid, increment)
            sim.initialize_field(INJECT_AS[component], cb)
            misses += stats["misses"]

        if method == "python":
            # read the corrected field on the Yee lattice
            e = np.array([[sim.fields.get_field(
                component, mp.vec(float(x), float(y))).real
                for y in grid.ys] for x in grid.xs])
            acc += dt * (math.cos(omega * n * dt) - 0.25) * e

    # The DFT accumulator advanced during the loop above whether or not we use
    # it.  It MUST be consumed, or the next apply_pi differences against a
    # stale baseline and silently absorbs this window.
    dft_window = wh.filter.read(half_step_shift=False)

    if method == "python":
        pi0 = (2.0 / T) * acc
    else:
        C = -(2.0 * dt * dt / (T * eps)) * sum(
            (math.cos(omega * n * dt) - 0.25)
            * forcing_amplitude(forcing, omega, dt, n)
            for n in range(1, M + 1)
        )
        pi0 = dft_window[component] + C * J

    if report is not None:
        report.update(misses=misses, dt=dt, M=M, forcing=forcing, method=method)

    out = wh.zero()
    out[component] = pi0
    return out
